export interface RuntimeInfo {
  nodeVersion?: string;
  platform?: string;
  pid?: number;
  hostname?: string;
}

export interface ToolExecution {
  id: string;
  tool: string;
  command: string;
  success: boolean;
  stdout?: string;
  stderr?: string;
  duration?: number;
  timestamp: number;
}

export interface IncidentOperation {
  id: string;

  step:
  | "coordinator"
  | "classify"
  | "diagnose"
  | "planning"
  | "approval"
  | "execute"
  | "verify";

  title: string;

  status:
  | "running"
  | "completed"
  | "failed"
  | "waiting";

  timestamp: number;

  duration?: number;

  details?: string;
}

export interface Incident {
  id: string;
  service: string;
  message: string;
  /** Title is derived from the message by the Runtime; not required from callers. */
  title?: string;
  severity?: "P1" | "P2" | "P3" | "P4";
  // From SDK payload
  stack?: string;
  runtime?: RuntimeInfo;
  environment?: string;
  metadata?: Record<string, unknown>;
  timestamp?: string;
  toolExecutions?: ToolExecution[];
  // From Classifier Agent
  category?: string;
  classifierService?: string;
  classifierConfidence?: number;
  // From Diagnosis Agent
  rootCause?: string;
  affectedService?: string;
  recommendation?: string;
  logs: {
    timestamp: string;
    level: "INFO" | "WARN" | "ERROR";
    message: string;
  }[];
  status:
  | "OPEN"
  | "TRIAGING"
  | "PLANNING"
  | "EXECUTING"
  | "RESOLVED"
  | "DIAGNOSING"
  | "DIAGNOSED"
  | "FAILED"
  | "AWAITING_REVIEW"
  | "AWAITING_APPROVAL";
  failureReason?: string;
  failedStep?: string;
  retryCount?: number;
  // Decision Gateway — set when a runbook's risk tier requires human approval
  /** Mastra workflow runId, used to resume the suspended run after a decision. */
  pendingRunId?: string;
  runbookId?: string;
  riskTier?: string;
  approvalReason?: string;
  /** Plain-English remediation plan narrative, generated by the Planning Agent. */
  plan?: string;
  metrics?: {
    cpu: number;
    memory: number;
    errorRate: number;
    latency: number;
    redisStatus?: string;
  };
  operationsLog?: IncidentOperation[];
  createdAt: Date;
  /** Set when the incident reaches RESOLVED — used for average-resolution-time stats. */
  resolvedAt?: number;
  trace?: {
    traceId: string;
    spanId?: string;
  };
  llm?: {
    provider: string;
    model?: string;
    attempts?: number;
    latency?: number;
  }
  /**
   * Runbook-specific real telemetry (e.g. Redis ping latency/connections,
   * Node current/required version). Generic on purpose — only runbooks that
   * have a natural telemetry shape populate it; others simply omit it rather
   * than fabricating values. See src/runbooks/*.ts.
   */
  telemetry?: Record<string, unknown>;
}
